<div class="row">
    <?php
    foreach ($events as $event) {
    ?>
    <div class="col-md-4 event" data-id="<?php echo $event->getId()?>">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $event->getName(); ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $event->getShortDescription(); ?></p>
                <p><button class="btn btn-success pull-right modalInfoShow" data-toggle="modal" data-target="#modalInfo">See detail &raquo;</button></p>
            </div>
            <div class="panel-footer text-muted">
                <?php echo $event->getDate()->format('Y-m-d H:i');?>
            </div>
        </div>
    </div>
    <?php }?>

    <div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalInfoTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p id="fullDescription"></p>
                    <br>
                    <?php
                    echo $this->form()->openTag($form);
                    ?>
                    <form id="clientForm">
                        <?php echo $this->formRow($form->get('event')); ?>
                        <div class="form-group">
                            <label for="clientFormFullName">Full name</label>
                            <?php echo $this->formRow($form->get('name')); ?>
                        </div>
                        <div class="form-group">
                            <label for="clientFormEmail">Email address</label>
                            <?php echo $this->formRow($form->get('email')); ?>
                        </div>
                        <?php
                        echo $this->form()->closeTag();
                        ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <?php echo $this->formSubmit($form->get('submit')); ?>
<!--                    <button type="submit" form="clientForm" class="btn btn-primary">Submit</button>-->
                </div>
            </div>
        </div>
    </div>
</div>
