<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Full name</th>
        <th scope="col">Email</th>
        <th scope="col">Events</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($clients as $client) {
    ?>
    <tr>
        <th scope="row"><?php echo $client->getId()?></th>
        <td><?php echo $client->getName()?></td>
        <td><?php echo $client->getEmail()?></td>
        <td><?php echo $client->getEvent()->getName()?></td>
    </tr>
    <?php
    }
    ?>
    </tbody>
</table>